name: Unit Tests
# Only test on master
on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest
      - name: Lint with pylint
        run: |
          # stop the build if the pylint score is under 8
          python -m pylint --fail-under=8 treasuremap main.py main_tkinter.py
      - name: Test with pytest
        run: |
          python -m pytest --junitxml=report.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'report.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
